name: build react app workflow
on: push
jobs:
  test-react:
    runs-on: ubuntu-latest
    steps:
    - name: checkout code
      uses: actions/checkout@v3
    - name: install dependencies
      run: npm i
    - name: test app
      run: npm test
