name: build react app workflow
on: push
jobs:
  test-react-job:
    runs-on: ubuntu-latest
    steps:
    - name: checkout code
      uses: actions/checkout@v3
    - name: install dependencies
      working-directory: ./hello-world
      run: npm i
    # - name: test app
    #   working-directory: ./hello-world
    #   run: npm test
